### ISSUE TITLE
Obliterator question

### ISSUE THREAD

**Issue by Zelvusenka** [JereKuusela/valheim-save_recovery#1]
Hello, I'm currently in the process of fixing my corrupted saves, and I have a question about the Obliterator. In your readme, you mentioned that we should be cautious of increasing the limit on crafting structures via mods. While I don't have any mods that do that, I was wondering about the Obliterator. On the Valheim wiki, it is listed under crafting structures, and it has a chest-sized inventory. So, if it gets filled with stacks of items (50), it easily exceeds the 255 value limit.

Additionally, I have a minor question. I am using the RelicHeim mod with Epic Loot included. My partner and I have spawned many bounties on the map. Am I correct in assuming that these bounties count towards the spawned creatures?

Lastly, we have a large number of tamed wolves gathered in one spot. Could this also be a potential issue?

Thank you for your time and for providing a mod that gives us hope to continue playing. :)

**Comment by JereKuusela** [comment]
Inventories should get saved properly. The limit is for structures with queues instead of an inventory.

I don't know how bounties are implemented but unlikely that they would use the zone spawn system.

Creatures itself don't count. The corruption is caused by different possible creatures that can randomly spawn.

**Comment by Zelvusenka** [comment]
Dear Jere,
is there known information regarding the "different creature limit" on ZDO. Specifically, I'm interested in determining the number of monsters we "can" encounter eg. in a swamp biome (vanilla+mods). Is it possible to know whether the stream can be read up to number of ten different spawns, but 11 is too much? 
Is it possible for the "random spawn" feature to be influenced and regulated by specific numbers? For example, instead of spawning 1-2 chickens, would it be possible to limit it to only 1 chicken near the player?

We have been using Majestic's Relicheim and have been experiencing similar save corruption issues as he described on discord. 

After utilizing the Save recovery tool and upgrade world, the save file is converted to match the conditions of patch 0.216.9. The game launched  successfully. In a single-player it works fine. I save the game, relaunch it, and everything continues to function properly. I also open the server and test it with two players, traveling through portals, visiting the crypt, and completing bounties. I save the game again, relaunch it, and everything is still working fine. However, when the server is opened and three players engage in gameplay for a couple of hours (visiting more biomes), the save becomes corrupted.
